version: "3"
services:
  postgres:
    image:  postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass123
    container_name: matcher_postgres
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    container_name: matcher_redis
volumes:
  pgdata:
